<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304130820 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_id VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AB2A824D8 ON companies (tax_id)');
        $this->addSql('CREATE TABLE ports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_899FD0CD77153098 ON ports (code)');
        $this->addSql('CREATE TABLE vessels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, imo VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, flag VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C34D3C0DB519409E ON vessels (imo)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE ports');
        $this->addSql('DROP TABLE vessels');
    }
}
